-- ============================================================
-- STUART MOTOS - SUPABASE SCHEMA
-- PostgreSQL + Auth + RLS + venda transacional
-- ============================================================

create extension if not exists pgcrypto;

-- ============================================================
-- PAPÉIS
-- ============================================================

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('owner')),
  created_at timestamptz not null default now()
);

alter table public.user_roles enable row level security;

create or replace function public.is_owner()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.user_roles
    where user_id = (select auth.uid())
      and role = 'owner'
  );
$$;

revoke all on function public.is_owner() from public;
grant execute on function public.is_owner() to authenticated;

-- ============================================================
-- PRODUTOS
-- ============================================================

create table if not exists public.produtos (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  categoria text not null,
  marca text,
  sku text,
  preco numeric(12,2) not null default 0 check (preco >= 0),
  quantidade integer not null default 0 check (quantidade >= 0),
  estoque_minimo integer not null default 0 check (estoque_minimo >= 0),
  ativo boolean not null default true,
  criado_por uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists produtos_sku_unique
on public.produtos (sku)
where sku is not null and sku <> '';

alter table public.produtos enable row level security;

-- ============================================================
-- VEÍCULOS
-- ============================================================

create table if not exists public.veiculos (
  id uuid primary key default gen_random_uuid(),
  marca text not null,
  modelo text not null,
  ano integer not null check (ano between 1950 and 2100),
  cor text,
  quilometragem integer not null default 0 check (quilometragem >= 0),
  preco numeric(12,2) not null default 0 check (preco >= 0),
  placa text,
  renavam text,
  observacoes text,
  vendido boolean not null default false,
  publicado boolean not null default true,
  criado_por uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists veiculos_placa_unique
on public.veiculos (upper(placa))
where placa is not null and placa <> '';

alter table public.veiculos enable row level security;

-- ============================================================
-- HORÁRIOS
-- ============================================================

create table if not exists public.horarios (
  dia_semana smallint primary key check (dia_semana between 0 and 6),
  nome_dia text not null,
  aberto boolean not null default true,
  hora_abertura time not null default '08:00',
  hora_fechamento time not null default '20:00',
  updated_at timestamptz not null default now(),
  constraint horario_valido check (
    aberto = false or hora_fechamento > hora_abertura
  )
);

alter table public.horarios enable row level security;

insert into public.horarios (dia_semana,nome_dia,aberto,hora_abertura,hora_fechamento)
values
  (0,'Domingo',false,'08:00','20:00'),
  (1,'Segunda',true,'08:00','20:00'),
  (2,'Terça',true,'08:00','20:00'),
  (3,'Quarta',true,'08:00','20:00'),
  (4,'Quinta',true,'08:00','20:00'),
  (5,'Sexta',true,'08:00','20:00'),
  (6,'Sábado',true,'08:00','20:00')
on conflict (dia_semana) do nothing;

-- ============================================================
-- CLIENTES
-- ============================================================

create table if not exists public.clientes (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  cpf_cnpj text,
  telefone text,
  email text,
  endereco text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.clientes enable row level security;

-- ============================================================
-- VENDAS
-- ============================================================

create table if not exists public.vendas (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  cliente_id uuid references public.clientes(id) on delete restrict,
  veiculo_id uuid references public.veiculos(id) on delete restrict,
  forma_pagamento text not null default 'PIX',
  subtotal_produtos numeric(12,2) not null default 0 check (subtotal_produtos >= 0),
  subtotal_servicos numeric(12,2) not null default 0 check (subtotal_servicos >= 0),
  subtotal_veiculo numeric(12,2) not null default 0 check (subtotal_veiculo >= 0),
  desconto numeric(12,2) not null default 0 check (desconto >= 0),
  total numeric(12,2) not null default 0 check (total >= 0),
  observacoes text,
  criado_por uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists venda_veiculo_unica
on public.vendas (veiculo_id)
where veiculo_id is not null;

alter table public.vendas enable row level security;

create table if not exists public.itens_venda (
  id uuid primary key default gen_random_uuid(),
  venda_id uuid not null references public.vendas(id) on delete cascade,
  produto_id uuid references public.produtos(id) on delete restrict,
  descricao text not null,
  quantidade integer not null check (quantidade > 0),
  valor_unitario numeric(12,2) not null check (valor_unitario >= 0),
  valor_total numeric(12,2) not null check (valor_total >= 0),
  created_at timestamptz not null default now()
);

alter table public.itens_venda enable row level security;

create table if not exists public.servicos_venda (
  id uuid primary key default gen_random_uuid(),
  venda_id uuid not null references public.vendas(id) on delete cascade,
  descricao text not null,
  quantidade integer not null check (quantidade > 0),
  valor_unitario numeric(12,2) not null check (valor_unitario >= 0),
  valor_total numeric(12,2) not null check (valor_total >= 0),
  created_at timestamptz not null default now()
);

alter table public.servicos_venda enable row level security;

-- ============================================================
-- UPDATED_AT
-- ============================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists produtos_updated_at on public.produtos;
create trigger produtos_updated_at before update on public.produtos
for each row execute function public.set_updated_at();

drop trigger if exists veiculos_updated_at on public.veiculos;
create trigger veiculos_updated_at before update on public.veiculos
for each row execute function public.set_updated_at();

drop trigger if exists horarios_updated_at on public.horarios;
create trigger horarios_updated_at before update on public.horarios
for each row execute function public.set_updated_at();

drop trigger if exists clientes_updated_at on public.clientes;
create trigger clientes_updated_at before update on public.clientes
for each row execute function public.set_updated_at();

drop trigger if exists vendas_updated_at on public.vendas;
create trigger vendas_updated_at before update on public.vendas
for each row execute function public.set_updated_at();

-- ============================================================
-- RLS
-- ============================================================

drop policy if exists "public_select_produtos" on public.produtos;
create policy "public_select_produtos"
on public.produtos for select
to anon, authenticated
using (ativo = true or (select public.is_owner()));

drop policy if exists "owner_manage_produtos" on public.produtos;
create policy "owner_manage_produtos"
on public.produtos for all
to authenticated
using ((select public.is_owner()))
with check ((select public.is_owner()));

drop policy if exists "public_select_veiculos" on public.veiculos;
create policy "public_select_veiculos"
on public.veiculos for select
to anon, authenticated
using (
  (publicado = true and vendido = false)
  or (select public.is_owner())
);

drop policy if exists "owner_manage_veiculos" on public.veiculos;
create policy "owner_manage_veiculos"
on public.veiculos for all
to authenticated
using ((select public.is_owner()))
with check ((select public.is_owner()));

drop policy if exists "public_select_horarios" on public.horarios;
create policy "public_select_horarios"
on public.horarios for select
to anon, authenticated
using (true);

drop policy if exists "owner_manage_horarios" on public.horarios;
create policy "owner_manage_horarios"
on public.horarios for all
to authenticated
using ((select public.is_owner()))
with check ((select public.is_owner()));

drop policy if exists "owner_manage_clientes" on public.clientes;
create policy "owner_manage_clientes"
on public.clientes for all
to authenticated
using ((select public.is_owner()))
with check ((select public.is_owner()));

drop policy if exists "owner_manage_vendas" on public.vendas;
create policy "owner_manage_vendas"
on public.vendas for all
to authenticated
using ((select public.is_owner()))
with check ((select public.is_owner()));

drop policy if exists "owner_manage_itens" on public.itens_venda;
create policy "owner_manage_itens"
on public.itens_venda for all
to authenticated
using ((select public.is_owner()))
with check ((select public.is_owner()));

drop policy if exists "owner_manage_servicos" on public.servicos_venda;
create policy "owner_manage_servicos"
on public.servicos_venda for all
to authenticated
using ((select public.is_owner()))
with check ((select public.is_owner()));

-- ============================================================
-- GRANTS PARA DATA API
-- ============================================================

grant select on public.produtos to anon, authenticated;
grant insert, update, delete on public.produtos to authenticated;

-- Visitante só recebe colunas públicas dos veículos.
revoke all on public.veiculos from anon;
grant select (
  id, marca, modelo, ano, cor, quilometragem, preco,
  observacoes, vendido, publicado, created_at, updated_at
) on public.veiculos to anon;

grant select, insert, update, delete on public.veiculos to authenticated;

grant select on public.horarios to anon, authenticated;
grant insert, update, delete on public.horarios to authenticated;

grant select, insert, update, delete on public.clientes to authenticated;
grant select, insert, update, delete on public.vendas to authenticated;
grant select, insert, update, delete on public.itens_venda to authenticated;
grant select, insert, update, delete on public.servicos_venda to authenticated;

revoke all on public.user_roles from anon, authenticated;

-- ============================================================
-- VENDA ATÔMICA / SEGURA
-- O cliente envia IDs/quantidades. O banco usa os preços reais
-- dos produtos e do veículo, atualiza estoque e grava tudo na
-- mesma transação.
-- ============================================================

create or replace function public.registrar_venda(
  p_cliente jsonb,
  p_produtos jsonb default '[]'::jsonb,
  p_servicos jsonb default '[]'::jsonb,
  p_veiculo_id uuid default null,
  p_forma_pagamento text default 'PIX',
  p_desconto numeric default 0,
  p_observacoes text default null
)
returns table (
  venda_id uuid,
  numero bigint,
  total numeric
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_cliente_id uuid;
  v_venda_id uuid;
  v_numero bigint;

  v_sub_prod numeric(12,2) := 0;
  v_sub_serv numeric(12,2) := 0;
  v_sub_vehicle numeric(12,2) := 0;
  v_total numeric(12,2) := 0;

  v_item jsonb;
  v_prod_id uuid;
  v_qty integer;
  v_service_price numeric(12,2);
  v_line_total numeric(12,2);

  v_product record;
  v_vehicle record;
begin
  if not public.is_owner() then
    raise exception 'Somente o dono pode registrar vendas';
  end if;

  if coalesce(trim(p_cliente->>'nome'),'') = '' then
    raise exception 'Nome do cliente é obrigatório';
  end if;

  if jsonb_array_length(coalesce(p_produtos,'[]'::jsonb)) = 0
     and jsonb_array_length(coalesce(p_servicos,'[]'::jsonb)) = 0
     and p_veiculo_id is null then
    raise exception 'A venda precisa ter produto, serviço ou veículo';
  end if;

  if coalesce(p_desconto,0) < 0 then
    raise exception 'Desconto inválido';
  end if;

  insert into public.clientes (
    nome, cpf_cnpj, telefone, email, endereco
  ) values (
    trim(p_cliente->>'nome'),
    nullif(trim(p_cliente->>'cpf_cnpj'),''),
    nullif(trim(p_cliente->>'telefone'),''),
    nullif(trim(p_cliente->>'email'),''),
    nullif(trim(p_cliente->>'endereco'),'')
  )
  returning id into v_cliente_id;

  if p_veiculo_id is not null then
    select *
      into v_vehicle
      from public.veiculos
     where id = p_veiculo_id
     for update;

    if not found then
      raise exception 'Veículo não encontrado';
    end if;

    if v_vehicle.vendido then
      raise exception 'Veículo já foi vendido';
    end if;

    v_sub_vehicle := v_vehicle.preco;
  end if;

  insert into public.vendas (
    cliente_id,
    veiculo_id,
    forma_pagamento,
    subtotal_produtos,
    subtotal_servicos,
    subtotal_veiculo,
    desconto,
    total,
    observacoes,
    criado_por
  ) values (
    v_cliente_id,
    p_veiculo_id,
    coalesce(nullif(trim(p_forma_pagamento),''),'PIX'),
    0,0,v_sub_vehicle,
    coalesce(p_desconto,0),
    0,
    p_observacoes,
    auth.uid()
  )
  returning id, public.vendas.numero
  into v_venda_id, v_numero;

  for v_item in
    select value from jsonb_array_elements(coalesce(p_produtos,'[]'::jsonb))
  loop
    v_prod_id := (v_item->>'produto_id')::uuid;
    v_qty := greatest(coalesce((v_item->>'quantidade')::integer,1),1);

    select id,nome,preco,quantidade,ativo
      into v_product
      from public.produtos
     where id = v_prod_id
     for update;

    if not found then
      raise exception 'Produto não encontrado';
    end if;

    if not v_product.ativo then
      raise exception 'Produto % está inativo', v_product.nome;
    end if;

    if v_product.quantidade < v_qty then
      raise exception 'Estoque insuficiente para %', v_product.nome;
    end if;

    v_line_total := v_product.preco * v_qty;
    v_sub_prod := v_sub_prod + v_line_total;

    insert into public.itens_venda (
      venda_id, produto_id, descricao, quantidade,
      valor_unitario, valor_total
    ) values (
      v_venda_id, v_product.id, v_product.nome, v_qty,
      v_product.preco, v_line_total
    );

    update public.produtos
       set quantidade = quantidade - v_qty
     where id = v_product.id;
  end loop;

  for v_item in
    select value from jsonb_array_elements(coalesce(p_servicos,'[]'::jsonb))
  loop
    if coalesce(trim(v_item->>'descricao'),'') = '' then
      raise exception 'Descrição da mão de obra é obrigatória';
    end if;

    v_qty := greatest(coalesce((v_item->>'quantidade')::integer,1),1);
    v_service_price := coalesce((v_item->>'valor_unitario')::numeric,0);

    if v_service_price < 0 then
      raise exception 'Valor de mão de obra inválido';
    end if;

    v_line_total := v_service_price * v_qty;
    v_sub_serv := v_sub_serv + v_line_total;

    insert into public.servicos_venda (
      venda_id, descricao, quantidade, valor_unitario, valor_total
    ) values (
      v_venda_id,
      trim(v_item->>'descricao'),
      v_qty,
      v_service_price,
      v_line_total
    );
  end loop;

  if p_veiculo_id is not null then
    update public.veiculos
       set vendido = true
     where id = p_veiculo_id;
  end if;

  v_total := greatest(
    0,
    v_sub_prod + v_sub_serv + v_sub_vehicle - coalesce(p_desconto,0)
  );

  update public.vendas
     set subtotal_produtos = v_sub_prod,
         subtotal_servicos = v_sub_serv,
         subtotal_veiculo = v_sub_vehicle,
         total = v_total
   where id = v_venda_id;

  return query
    select v_venda_id, v_numero, v_total;
end;
$$;

revoke all on function public.registrar_venda(jsonb,jsonb,jsonb,uuid,text,numeric,text) from public;
grant execute on function public.registrar_venda(jsonb,jsonb,jsonb,uuid,text,numeric,text) to authenticated;

-- ============================================================
-- ÍNDICES
-- ============================================================

create index if not exists produtos_nome_idx on public.produtos (nome);
create index if not exists produtos_categoria_idx on public.produtos (categoria);
create index if not exists veiculos_marca_modelo_idx on public.veiculos (marca,modelo);
create index if not exists vendas_created_at_idx on public.vendas (created_at desc);
create index if not exists itens_venda_venda_idx on public.itens_venda (venda_id);
create index if not exists servicos_venda_venda_idx on public.servicos_venda (venda_id);
